import type { Metadata } from 'next';
import { Playfair_Display } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';

const playMono = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  variable: '--font-playfair',
});

const playSans = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  variable: '--font-popsans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playSans.variable} ${playMono.variable} antialiased`}>
        <AntdRegistry>
          <div className="max-w-300 overflow-hidden mx-auto bg-amber-900">
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
